import 'base_response_model.dart';

class AdminProductListResponse extends BaseApiResponseModel<List<AdminProduct>> {
  final int page;
  final int limit;
  final int totalPages;

  const AdminProductListResponse({
    required super.success,
    required super.message,
    required this.page,
    required this.limit,
    required this.totalPages,
    super.data,
  });

  factory AdminProductListResponse.fromJson(Map<String, dynamic> json) {
    return AdminProductListResponse(
      success: (json['is_success'] as bool?) ?? false,
      message: json['message'] ?? '',
      page: json['page'] as int? ?? 1,
      limit: json['limit'] as int? ?? 10,
      totalPages: json['total_pages'] as int? ?? json['totalPages'] as int? ?? 1,
      data: json['data'] == null
          ? null
          : (json['data'] as List)
              .map((e) => AdminProduct.fromJson(e as Map<String, dynamic>))
              .toList(),
    );
  }
}

class AdminProduct {
  final int id;
  final String image;
  final String name;
  final String? brand;
  final String? manufacturer;
  final String? globalSku;
  final String? usageType;
  final String? category;
  final List<int> selectedCategoryIds;
  final String? status;
  final String description;
  final String? unitType;
  final int? boxQuantity;
  final int? itemQuantityPerBox;
  final String? packageType;
  final String? billableUnit;
  final double? billableQuantityPerItem;
  final double? totalBillableQuantity;
  final bool enforceLotTracking;

  const AdminProduct({
    required this.id,
    required this.image,
    required this.name,
    this.brand,
    this.manufacturer,
    this.globalSku,
    this.usageType,
    this.category,
    required this.selectedCategoryIds,
    this.status,
    required this.description,
    this.unitType,
    this.boxQuantity,
    this.itemQuantityPerBox,
    this.packageType,
    this.billableUnit,
    this.billableQuantityPerItem,
    this.totalBillableQuantity,
    required this.enforceLotTracking,
  });

  factory AdminProduct.fromJson(Map<String, dynamic> json) {
    return AdminProduct(
      id: json['id'] as int? ?? 0,
      image: json['image'] ?? '',
      name: json['name'] ?? '',
      brand: json['brand'],
      manufacturer: json['manufacturer'],
      globalSku: json['global_sku'] ?? json['globalSku'],
      usageType: json['usage_type'] ?? json['usageType'],
      category: json['category'],
      selectedCategoryIds: json['selected_category_ids'] != null
          ? List<int>.from(json['selected_category_ids'])
          : json['selectedCategoryIds'] != null
              ? List<int>.from(json['selectedCategoryIds'])
              : [],
      status: json['status'],
      description: json['description'] ?? '',
      unitType: json['unit_type'] ?? json['unitType'],
      boxQuantity: json['box_quantity'] as int? ?? json['boxQuantity'] as int?,
      itemQuantityPerBox: json['item_quantity_per_box'] as int? ?? json['itemQuantityPerBox'] as int?,
      packageType: json['package_type'] ?? json['packageType'],
      billableUnit: json['billable_unit'] ?? json['billableUnit'],
      billableQuantityPerItem: (json['billable_quantity_per_item'] as num?)?.toDouble() ?? (json['billableQuantityPerItem'] as num?)?.toDouble(),
      totalBillableQuantity: (json['total_billable_quantity'] as num?)?.toDouble() ?? (json['totalBillableQuantity'] as num?)?.toDouble(),
      enforceLotTracking: json['enforce_lot_tracking'] as bool? ?? json['enforceLotTracking'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'image': image,
      'name': name,
      'brand': brand,
      'manufacturer': manufacturer,
      'global_sku': globalSku,
      'usage_type': usageType,
      'category': category,
      'selected_category_ids': selectedCategoryIds,
      'status': status,
      'description': description,
      'unit_type': unitType,
      'box_quantity': boxQuantity,
      'item_quantity_per_box': itemQuantityPerBox,
      'package_type': packageType,
      'billable_unit': billableUnit,
      'billable_quantity_per_item': billableQuantityPerItem,
      'total_billable_quantity': totalBillableQuantity,
      'enforce_lot_tracking': enforceLotTracking,
    };
  }
}

class AdminDummyProducts {
  static List<AdminProduct> getDummyProductsForPage(int page, int limit) {
    final allProducts = [
      // Page 1
      const AdminProduct(
        id: 1,
        image: 'https://example.com/product1.png',
        name: 'Juvederm Ultra XC',
        brand: 'Allergan',
        manufacturer: 'AbbVie Inc.',
        globalSku: 'PRD-0001-JUVD',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Hyaluronic acid filler for lip augmentation and moderate facial wrinkles.',
        unitType: 'syringe',
        boxQuantity: 10,
        itemQuantityPerBox: 2,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 20.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 2,
        image: 'https://example.com/product2.png',
        name: 'Botox Cosmetic 100U',
        brand: 'Allergan',
        manufacturer: 'AbbVie Inc.',
        globalSku: 'PRD-0002-BOTOX',
        usageType: 'treatment',
        category: 'Neuromodulators',
        selectedCategoryIds: [1, 3],
        status: 'active',
        description: 'OnabotulinumtoxinA injection for temporary improvement of frown lines.',
        unitType: 'vial',
        boxQuantity: 5,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'unit',
        billableQuantityPerItem: 100.0,
        totalBillableQuantity: 500.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 3,
        image: 'https://example.com/product3.png',
        name: 'Restylane Lyft 1mL',
        brand: 'Galderma',
        manufacturer: 'Galderma Laboratories',
        globalSku: 'PRD-0003-REST',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Deep hyaluronic acid filler for cheek augmentation and mid-face contouring.',
        unitType: 'syringe',
        boxQuantity: 10,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 10.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 4,
        image: 'https://example.com/product4.png',
        name: 'Sculptra Aesthetic',
        brand: 'Galderma',
        manufacturer: 'Galderma Laboratories',
        globalSku: 'PRD-0004-SCULP',
        usageType: 'treatment',
        category: 'Skinboosters',
        selectedCategoryIds: [1, 4],
        status: 'active',
        description: 'Poly-L-lactic acid (PLLA) collagen stimulator to restore facial volume.',
        unitType: 'vial',
        boxQuantity: 2,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'vial',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 2.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 5,
        image: 'https://example.com/product5.png',
        name: 'Dysport 300U',
        brand: 'Galderma',
        manufacturer: 'Ipsen Biopharm',
        globalSku: 'PRD-0005-DYSP',
        usageType: 'treatment',
        category: 'Neuromodulators',
        selectedCategoryIds: [1, 3],
        status: 'active',
        description: 'AbobotulinumtoxinA injection for professional glabellar lines correction.',
        unitType: 'vial',
        boxQuantity: 10,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'unit',
        billableQuantityPerItem: 300.0,
        totalBillableQuantity: 3000.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 6,
        image: 'https://example.com/product6.png',
        name: 'Xeomin 100U',
        brand: 'Merz Aesthetics',
        manufacturer: 'Merz Pharmaceuticals',
        globalSku: 'PRD-0006-XEOM',
        usageType: 'treatment',
        category: 'Neuromodulators',
        selectedCategoryIds: [1, 3],
        status: 'active',
        description: 'IncobotulinumtoxinA purified neurotoxin injection without unnecessary proteins.',
        unitType: 'vial',
        boxQuantity: 5,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'unit',
        billableQuantityPerItem: 100.0,
        totalBillableQuantity: 500.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 7,
        image: 'https://example.com/product7.png',
        name: 'Radiesse (+) 1.5cc',
        brand: 'Merz Aesthetics',
        manufacturer: 'Merz North America',
        globalSku: 'PRD-0007-RADI',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Calcium hydroxylapatite injectable implant with integral lidocaine for jawline contouring.',
        unitType: 'syringe',
        boxQuantity: 5,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.5,
        totalBillableQuantity: 7.5,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 8,
        image: 'https://example.com/product8.png',
        name: 'Belotero Balance 1mL',
        brand: 'Merz Aesthetics',
        manufacturer: 'Merz Pharmaceuticals',
        globalSku: 'PRD-0008-BELO',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Cohesive hyaluronic acid gel designed for superficial lines and delicate skin areas.',
        unitType: 'syringe',
        boxQuantity: 10,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 10.0,
        enforceLotTracking: false,
      ),

      // Page 2
      const AdminProduct(
        id: 9,
        image: 'https://example.com/product9.png',
        name: 'Revanesse Versa 1mL',
        brand: 'Prollenium',
        manufacturer: 'Prollenium Medical',
        globalSku: 'PRD-0009-VERS',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Multi-purpose hyaluronic acid dermal filler designed for high volume retention and low swelling.',
        unitType: 'syringe',
        boxQuantity: 8,
        itemQuantityPerBox: 2,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 16.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 10,
        image: 'https://example.com/product10.png',
        name: 'Teosyal Redensity II',
        brand: 'Teoxane',
        manufacturer: 'Teoxane Laboratories',
        globalSku: 'PRD-0010-TEOS',
        usageType: 'treatment',
        category: 'Skinboosters',
        selectedCategoryIds: [1, 4],
        status: 'active',
        description: 'Aesthetic injectable treatment specializing in dark circles and tear trough hollow correction.',
        unitType: 'syringe',
        boxQuantity: 2,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 2.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 11,
        image: 'https://example.com/product11.png',
        name: 'Profhilo 2mL',
        brand: 'IBSA',
        manufacturer: 'IBSA Farmaceutici',
        globalSku: 'PRD-0011-PROF',
        usageType: 'treatment',
        category: 'Skinboosters',
        selectedCategoryIds: [1, 4],
        status: 'active',
        description: 'Bioremodeling hyaluronic acid treatment delivering intense skin hydration and elasticity recovery.',
        unitType: 'syringe',
        boxQuantity: 1,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 2.0,
        totalBillableQuantity: 2.0,
        enforceLotTracking: false,
      ),
      const AdminProduct(
        id: 12,
        image: 'https://example.com/product12.png',
        name: 'Juvéderm Voluma XC',
        brand: 'Allergan',
        manufacturer: 'AbbVie Inc.',
        globalSku: 'PRD-0012-VOLU',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Premium hyaluronic acid gel indicated for deep injection to restore cheek volume.',
        unitType: 'syringe',
        boxQuantity: 10,
        itemQuantityPerBox: 2,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 20.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 13,
        image: 'https://example.com/product13.png',
        name: 'Kybella 4x2mL',
        brand: 'Allergan',
        manufacturer: 'AbbVie Inc.',
        globalSku: 'PRD-0013-KYBE',
        usageType: 'treatment',
        category: 'Kybella',
        selectedCategoryIds: [1, 5],
        status: 'active',
        description: 'Deoxycholic acid clinical injection designed to destroy submental fat cells under the chin.',
        unitType: 'vial',
        boxQuantity: 4,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 2.0,
        totalBillableQuantity: 8.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 14,
        image: 'https://example.com/product14.png',
        name: 'Restylane Kysse 1mL',
        brand: 'Galderma',
        manufacturer: 'Galderma Laboratories',
        globalSku: 'PRD-0014-KYSS',
        usageType: 'treatment',
        category: 'Dermal Fillers',
        selectedCategoryIds: [1, 2],
        status: 'active',
        description: 'Hyaluronic acid gel with OBT technology designed specifically for soft and flexible lip projection.',
        unitType: 'syringe',
        boxQuantity: 10,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 10.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 15,
        image: 'https://example.com/product15.png',
        name: 'Sculptra (Reconstituted)',
        brand: 'Galderma',
        manufacturer: 'Galderma Laboratories',
        globalSku: 'PRD-0015-SCULP-REC',
        usageType: 'treatment',
        category: 'Skinboosters',
        selectedCategoryIds: [1, 4],
        status: 'active',
        description: 'Reconstituted collagen booster formula for facial volume restructuring.',
        unitType: 'vial',
        boxQuantity: 5,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'vial',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 5.0,
        enforceLotTracking: true,
      ),

      // Page 3
      const AdminProduct(
        id: 16,
        image: 'https://example.com/product16.png',
        name: 'Perfect Derma Peel',
        brand: 'Perfect Derma',
        manufacturer: 'Bella Medical Products',
        globalSku: 'PRD-0016-PEEL',
        usageType: 'treatment',
        category: 'Chemical Peels',
        selectedCategoryIds: [2, 1],
        status: 'active',
        description: 'Medical-grade medium depth chemical peel featuring Glutathione for anti-aging skin rejuvenation.',
        unitType: 'vial',
        boxQuantity: 1,
        itemQuantityPerBox: 1,
        packageType: 'kit',
        billableUnit: 'kit',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 1.0,
        enforceLotTracking: false,
      ),
      const AdminProduct(
        id: 17,
        image: 'https://example.com/product17.png',
        name: 'VI Peel Purify',
        brand: 'VI Peel',
        manufacturer: 'Vitality Institute',
        globalSku: 'PRD-0017-VIPE',
        usageType: 'treatment',
        category: 'Chemical Peels',
        selectedCategoryIds: [2, 1],
        status: 'active',
        description: 'Clinical peel targeting acne, scarring, and hyperpigmentation.',
        unitType: 'vial',
        boxQuantity: 1,
        itemQuantityPerBox: 1,
        packageType: 'kit',
        billableUnit: 'kit',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 1.0,
        enforceLotTracking: false,
      ),
      const AdminProduct(
        id: 18,
        image: 'https://example.com/product18.png',
        name: 'Aquagold Fine Touch',
        brand: 'Aquagold',
        manufacturer: 'Aquagold Inc.',
        globalSku: 'PRD-0018-GOLD',
        usageType: 'treatment',
        category: 'Microneedling',
        selectedCategoryIds: [2, 2],
        status: 'active',
        description: '24-karat gold-plated micro-injection device to deliver customized serum solutions.',
        unitType: 'vial',
        boxQuantity: 10,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'item',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 10.0,
        enforceLotTracking: false,
      ),
      const AdminProduct(
        id: 19,
        image: 'https://example.com/product19.png',
        name: 'SurgiMend Collagen 2x2',
        brand: 'SurgiMend',
        manufacturer: 'Integra LifeSciences',
        globalSku: 'PRD-0019-SURG',
        usageType: 'treatment',
        category: 'Skinboosters',
        selectedCategoryIds: [2, 3],
        status: 'active',
        description: 'Acellular dermal matrix collagen tissue graft.',
        unitType: 'item',
        boxQuantity: 1,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'item',
        billableQuantityPerItem: 1.0,
        totalBillableQuantity: 1.0,
        enforceLotTracking: true,
      ),
      const AdminProduct(
        id: 20,
        image: 'https://example.com/product20.png',
        name: 'HylaActive 30mL',
        brand: 'Dp Derm',
        manufacturer: 'DermapenWorld',
        globalSku: 'PRD-0020-HYLA',
        usageType: 'treatment',
        category: 'Microneedling',
        selectedCategoryIds: [2, 2],
        status: 'active',
        description: 'Intense hyaluronic acid skin infusion serum for post-needling application.',
        unitType: 'vial',
        boxQuantity: 1,
        itemQuantityPerBox: 1,
        packageType: 'box',
        billableUnit: 'ml',
        billableQuantityPerItem: 30.0,
        totalBillableQuantity: 30.0,
        enforceLotTracking: false,
      ),
    ];

    final startIdx = (page - 1) * limit;
    if (startIdx >= allProducts.length) return [];
    final endIdx = startIdx + limit > allProducts.length ? allProducts.length : startIdx + limit;
    return allProducts.sublist(startIdx, endIdx);
  }
}
